from flask import Flask, request, render_template, redirect, url_for, session, flash
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from src.pipeline.predict_pipeline import CustomData, PredictPipeline
from datetime import datetime
import pytz
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

ist = pytz.timezone('Asia/Kolkata')

def get_ist_time():
    return datetime.now(ist)

# ------------------- Flask App Configuration -------------------
app = Flask(__name__)

SUPABASE_DB_URL = os.environ.get(
    'DATABASE_URL',
    'postgresql://postgres.vkcdqpjcsyjmurcznlrt:Pratik5903%40@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres'
)

app.config['SQLALCHEMY_DATABASE_URI'] = SUPABASE_DB_URL
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_ENGINE_OPTIONS'] = {
    'pool_pre_ping': True,
    'pool_recycle': 300
}

app.secret_key = os.environ.get('SECRET_KEY', 'fallback_dev_key_change_in_prod')

app.config['SESSION_COOKIE_SECURE'] = False
app.config['SESSION_COOKIE_SAMESITE'] = 'Lax'
app.config['SESSION_COOKIE_HTTPONLY'] = True

db = SQLAlchemy(app)


# ------------------- Email Configuration -------------------
SENDER_EMAIL = os.environ.get('SENDER_EMAIL', 'pratikksecondaryacc@gmail.com')
APP_PASSWORD = os.environ.get('APP_PASSWORD', 'xtbzqqbisteqltzw')


def send_prediction_email(to_email, username, predicted_score, reading_score, writing_score):
    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f'🎯 EduScore.AI — Your Predicted Math Score: {predicted_score}'
        msg['From'] = SENDER_EMAIL
        msg['To'] = to_email

        # Determine grade label
        if predicted_score >= 75:
            grade = "Excellent 🌟"
            color = "#43e97b"
        elif predicted_score >= 50:
            grade = "Good 👍"
            color = "#ffc832"
        else:
            grade = "Needs Improvement 📚"
            color = "#ff5050"

        html = f"""
        <html>
        <body style="font-family: 'Poppins', sans-serif; background: #f4f4f4; padding: 30px;">
            <div style="max-width: 500px; margin: auto; background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1);">
                <div style="background: linear-gradient(135deg, #667eea, #764ba2); padding: 30px; text-align: center;">
                    <h1 style="color: white; margin: 0; font-size: 1.8rem;">EduScore.AI</h1>
                    <p style="color: rgba(255,255,255,0.85); margin: 5px 0 0;">Prediction Result</p>
                </div>
                <div style="padding: 30px;">
                    <p style="font-size: 1rem; color: #333;">Hey <strong>{username}</strong> 👋,</p>
                    <p style="color: #555;">Here's your predicted math score based on your inputs:</p>

                    <div style="text-align: center; margin: 25px 0;">
                        <div style="font-size: 3.5rem; font-weight: 700; color: {color};">{predicted_score}</div>
                        <div style="font-size: 1rem; color: #888; margin-top: 5px;">{grade}</div>
                    </div>

                    <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                        <tr style="background: #f9f9f9;">
                            <td style="padding: 10px; color: #555;">Reading Score</td>
                            <td style="padding: 10px; font-weight: 600; text-align: right;">{int(reading_score)}</td>
                        </tr>
                        <tr>
                            <td style="padding: 10px; color: #555;">Writing Score</td>
                            <td style="padding: 10px; font-weight: 600; text-align: right;">{int(writing_score)}</td>
                        </tr>
                        <tr style="background: #f9f9f9;">
                            <td style="padding: 10px; color: #555;">Predicted Math Score</td>
                            <td style="padding: 10px; font-weight: 600; text-align: right; color: {color};">{predicted_score}</td>
                        </tr>
                    </table>

                    <p style="color: #888; font-size: 0.85rem; margin-top: 25px; text-align: center;">
                        This prediction was generated by EduScore.AI using machine learning.
                    </p>
                </div>
            </div>
        </body>
        </html>
        """

        msg.attach(MIMEText(html, 'html'))

        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(SENDER_EMAIL, APP_PASSWORD)
            server.sendmail(SENDER_EMAIL, to_email, msg.as_string())

        print(f"✅ Email sent to {to_email}")

    except Exception as e:
        print(f"❌ Email failed: {e}")


# ------------------- Database Models -------------------

class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)

    def __repr__(self):
        return f'<User {self.username}>'


class Prediction(db.Model):
    __tablename__ = 'predictions'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, nullable=False)
    username = db.Column(db.String(100), nullable=False)
    gender = db.Column(db.String(20))
    race_ethnicity = db.Column(db.String(50))
    parental_education = db.Column(db.String(100))
    lunch = db.Column(db.String(50))
    test_prep = db.Column(db.String(50))
    reading_score = db.Column(db.Float)
    writing_score = db.Column(db.Float)
    predicted_score = db.Column(db.Float)
    created_at = db.Column(db.DateTime, default=get_ist_time)

    def __repr__(self):
        return f'<Prediction {self.username} - {self.predicted_score}>'


# ------------------- Home Route -------------------
@app.route('/')
def home():
    if 'user_id' not in session:
        flash("Please login first!", "warning")
        return redirect(url_for('login'))
    return render_template('home.html')


# ------------------- Registration -------------------
@app.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username'].strip()
        email = request.form['email'].strip()
        password = request.form['password']

        if User.query.filter_by(username=username).first():
            flash('Username already taken. Please choose another.', 'danger')
            return redirect(url_for('register'))

        if User.query.filter_by(email=email).first():
            flash('Email already registered. Please use another.', 'danger')
            return redirect(url_for('register'))

        hashed_password = generate_password_hash(password, method='pbkdf2:sha256', salt_length=8)

        try:
            new_user = User(username=username, email=email, password=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            flash('Registration successful! Please log in.', 'success')
            return redirect(url_for('login'))
        except Exception as e:
            db.session.rollback()
            flash('An unexpected error occurred. Please try again.', 'danger')
            print("Error during registration:", e)
            return redirect(url_for('register'))

    return render_template('register.html')


# ------------------- Login -------------------
@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if user and check_password_hash(user.password, password):
            session['user_id'] = user.id
            session['username'] = user.username
            session['email'] = user.email
            flash(f"Welcome back, {user.username}!", "success")
            return redirect('/')
        else:
            flash("Invalid email or password", "danger")
            return redirect(url_for('login'))

    return render_template('login.html')


# ------------------- Logout -------------------
@app.route('/logout')
def logout():
    session.clear()
    flash('Logged out successfully.', 'success')
    return redirect(url_for('login'))


# ------------------- Prediction -------------------
@app.route('/predictdata', methods=['GET', 'POST'])
def predict_datapoint():
    if 'user_id' not in session:
        flash("Please login first!", "warning")
        return redirect(url_for('login'))

    if request.method == 'GET':
        return render_template('home.html')

    gender = request.form.get('gender')
    race_ethnicity = request.form.get('ethnicity')
    parental_education = request.form.get('parental_level_of_education')
    lunch = request.form.get('lunch')
    test_prep = request.form.get('test_preparation_course')
    reading_score = float(request.form.get('reading_score'))
    writing_score = float(request.form.get('writing_score'))

    data = CustomData(
        gender=gender,
        race_ethnicity=race_ethnicity,
        parental_level_of_education=parental_education,
        lunch=lunch,
        test_preparation_course=test_prep,
        reading_score=reading_score,
        writing_score=writing_score
    )

    pred_df = data.get_data_as_data_frame()
    predict_pipeline = PredictPipeline()
    results = predict_pipeline.predict(pred_df)
    predicted_score = round(float(results[0]), 2)

    # ✅ Save prediction to Supabase
    try:
        new_prediction = Prediction(
            user_id=session['user_id'],
            username=session['username'],
            gender=gender,
            race_ethnicity=race_ethnicity,
            parental_education=parental_education,
            lunch=lunch,
            test_prep=test_prep,
            reading_score=reading_score,
            writing_score=writing_score,
            predicted_score=predicted_score
        )
        db.session.add(new_prediction)
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        print("Error saving prediction:", e)

    
    # ✅ Send email only when running locally (Render blocks Gmail port)
    if not os.environ.get('RENDER'):
        import threading
        TEACHER_EMAIL = "pratikksecondaryacc@gmail.com"
        thread = threading.Thread(target=send_prediction_email, args=(
            TEACHER_EMAIL,
            session['username'],
            predicted_score,
            reading_score,
            writing_score
        ))
        thread.daemon = True
        thread.start()

    return render_template('home.html', results=predicted_score)


# ------------------- Dashboard -------------------
@app.route('/dashboard')
def dashboard():
    if 'user_id' not in session:
        flash("Please login first!", "warning")
        return redirect(url_for('login'))

    predictions = Prediction.query.filter_by(
        user_id=session['user_id']
    ).order_by(Prediction.created_at.desc()).all()

    return render_template('dashboard.html', predictions=predictions)


# ------------------- App Runner -------------------
if __name__ == '__main__':
    with app.app_context():
        db.create_all()
        print("✅ Connected to Supabase & tables ready!")

    app.run(host='127.0.0.1', port=5000, debug=True)