services:
  - type: web
    name: eduscore-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.vkcdqpjcsyjmurcznlrt:Pratik5903%40@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
      - key: SECRET_KEY
        value: eduscore_secret_2025
      - key: SENDER_EMAIL
        value: pratikksecondaryacc@gmail.com
      - key: APP_PASSWORD
        value: xtbzqqbisteqltzw